### ISSUE TITLE
live recording module

### ISSUE THREAD

**Issue by diemoschwarz** [Ircam-RnD/catart-mubu#12]
- Switch refresh rate?

**Comment by einbond** [comment]
- imubu refresh rate switched, but maybe more elegant way to do this? instead of metro refresh after each marker?

**Comment by einbond** [comment]
This tutorial is nearly ready, but one minor issue I can't solve: either camu.record contains a mubu.record with @predef no and the patch opens with the following error message:

*mubu.process: invalid buffer index in message bang

Or mubu.record has @predef yes, there is no error message, but the live recording goes into buffer #2. Which do you prefer, or can anyone find a solution?

**Comment by diemoschwarz** [comment]
there must be some messages being sent on loadbang

**Comment by diemoschwarz** [comment]
yes, in analysis. fixed in 24c150bb6c
TODO: camu.analysis that has all that: #10
