### ISSUE TITLE
screensize

### ISSUE THREAD

**Issue by einbond** [Ircam-RnD/catart-mubu#21]
catart-by-mubu-simple.maxpat (and most other patches in this project) do not fit on a small laptop screen. If students at Darmstadt (and future users of camu in general) are using laptops, it could be nice if the basic patches fit automatically.

- consider resizing all simple patches to fit on Macbook Pro 13"?

**Comment by diemoschwarz** [comment]
+1

**Comment by christophertrapani** [comment]
+ 2

**Comment by einbond** [comment]
Done for catart-by-mubu-simple.maxpat! Now consider applying to other simple patches?
