### ISSUE TITLE
reorg example patches and tutorials

### ISSUE THREAD

**Issue by diemoschwarz** [Ircam-RnD/catart-mubu#23]
1. rename the catart-simple patches into tutorials
2. create 3 catart-simple patches:
2a. basic xy control
2b. live analysis (mosaicing)
2c. live recording
3. create targeted transposition and transcription example patches?

**Comment by einbond** [comment]
Question about basic tutorials: some patches could be decluttered by moving message boxes like "select $1 $2" and "columns $1 $2" into sub patches. Would this be a good idea, or is it desirable to have them exposed?

**Comment by christophertrapani** [comment]
I’ve been keeping everything exposed, and avoiding presentation mode (except in bpatchers) on the theory that this will make it easier for others to figure out what’s happening under the hood... it is cluttered, though...

**Comment by diemoschwarz** [comment]
the idea is to show them once (with explanation) and then hide them not to divert attention from the next bit of information. 
I haven't gone into colour for emphasis yet (the bubbles do that), but it would make the patches less austerely grey.  Any favourite colour?

**Comment by christophertrapani** [comment]
In my tutorials I tried to color all the newly-introduced objects so they’re immediately apparent. A light blue border or panel — though any color is fine...

**Comment by diemoschwarz** [comment]
hey guys, we're almost there! still missing is
  3. create targeted transposition and transcription tutorial patches?
and a catart-simple-live patch including
  2b. live analysis (mosaicing)
  2c. live recording
I reckon, point 2 is more involved than 3. 
Do you have some stub for a tutorial 9 for transcription and 8 targeted transposition?

**Comment by christophertrapani** [comment]
Tutorials 8 and 9 are done! And they're uploaded to the master branch on
github now...

**Comment by diemoschwarz** [comment]
let's refocus this issue on the tutorial patches, then we can close it!
The further todos for example patches are #30 (new live example patch) and #31 (new transcription example)
