### ISSUE TITLE
split camu.cont out of camu.triggermodes

### ISSUE THREAD

**Issue by diemoschwarz** [Ircam-RnD/catart-mubu#26]
cont mode is the only one needing (circular) connection to concat. should be separate patch, controlled  by triggermodes

**Comment by christophertrapani** [comment]
I see that "click mode" has also been restructured. In 1c "contclick" and "click" are remove from the trigger modes umenu, but in 1d they reappear. Should they be a.) permanently separated or b.) reconfigured so that camu.triggermode automatically turns click mode on and off?

**Comment by diemoschwarz** [comment]
click mode is orthogonal to trigger modes and should be removed from all the menus
