### ISSUE TITLE
The simple patch doesn't seem work in the latest Max?

### ISSUE THREAD

**Issue by yeswecan** [Ircam-RnD/catart-mubu#37]
Hello and sorry if this question is stupid, I'm not a pro in Max yet.

This simple example patch won't do anything after I load audio in the latest Max 8.0.8. It shows these errors:
![image](https://user-images.githubusercontent.com/1935529/63379747-9fcffa80-c39d-11e9-842b-897ca758dae9.png)

The `pipo.descr` module mentioned here is available and I can include it in patch myself. I'm not exactly sure how to debug this and sorry if it's obvious to you.

I'm on OSX 10.14.6

**Comment by diemoschwarz** [comment]
Hi, be sure to install the latest mubu 1.9.10 from http://forumnet.ircam.fr/product/mubu-en/ 

Hint: you can copy the text from the Max console, no need to use screenshots.
