### ISSUE TITLE
trigger modes

### ISSUE THREAD

**Issue by diemoschwarz** [Ircam-RnD/catart-mubu#4]
trigger mode switcher + pause/resume

**Comment by diemoschwarz** [comment]
- pause/resume for @play 1 modes
- click mode here?
- separate bpatchers for each trigger mode/descriptor list?

**Comment by einbond** [comment]
Done.

- Any reason to have a separate module (camu.trigger) or is a subpatch sufficient? In either case, click mode does not connect to the trigger subpatch, but to the target subpatch instead.

- What is the desirable behavior of pause/resume? Currently responds to trigger mode (e.g. changing fence to beat turns on "resume") but trigger mode does not respond to it (e.g. changing play 1 to 0 does not change beat to fence).

**Comment by einbond** [comment]
Or a different version exposing the triggering attruis in the main patch? See catart-by-mubu-trigger.2.maxpat

**Comment by einbond** [comment]
Working on another version, trigger.3 (we can choose our favorite later):

- click included as new trigger mode (paired with cont, which now also outputs only on mouse click)

- @diemoschwarz is there a difference between "play 0" and "stop" messages to mubu.concat? If not, it is confusing. As an alternative, "stop" could be a hard stop mid-marker, but it does not seem to be the case currently.
