### ISSUE TITLE
adding a z-axis for descriptors, for playing 3D timbre spaces in VR

### ISSUE THREAD

**Issue by michaelpalumbo** [Ircam-RnD/catart-mubu#40]
Hi Diemo, I was at your workshop in Dispersion Lab last month (and am a friend of Glen's). 

I'm involved in a project which will be experimenting with concatenative synthesis in VR, and am curious about adding a z-axis for descriptors. 

Seems like I could hack on [camu.menu] and the [p imubu-setup] to achieve this, but I wondered if you had any ideas or foresee any difficulties? Am happy to keep you posted of our progress :)

**Comment by diemoschwarz** [comment]
Hi Michael, thanks for the follow-up!
There should be no difficulty at all on the catart-mubu side, just send in one more item with the "columns" and "select" messages for the 3rd dimension.
Visualizing it is up to you =-).
Just be aware that the space gets less dense with every added dimension, so there will be ever larger empty regions.  Here, k > 1  and radius are your friend. We're also pretty close to integrating pca witih catart.
Be sure to let us know how you progress!
Oh, and interesting questions like this are best asked on the https://forum.ircam.fr/projects/detail/catart-mubu/ discussion groups. Would you mind reposting there?

**Comment by michaelpalumbo** [comment]
Thanks @diemoschwarz I'll post to the forums now.
