### ISSUE TITLE
decide, design, and add catart-mubu icon

### ISSUE THREAD

**Issue by diemoschwarz** [Ircam-RnD/catart-mubu#60]
https://cycling74.com/tutorials/package-authoring-the-finer-details:
> Every Package installed for your copy of Max or available through the Package Manager will have a cover image that helps to identify the Package. This image should be a PNG graphics file 500x500 pixels in size and should be named "icon.png". It should be located at the top level of your Package folder.

some possibilities:
1. catart-app 2014 icon: 
   <img height=200 src="https://user-images.githubusercontent.com/378151/185257616-cce1b7b9-e3a1-4aa9-ba0f-81a5ed36677b.png"/> 
3. ismm logo style (only works for 4 letters...), e.g.: 
![image](https://user-images.githubusercontent.com/378151/185258236-1c5f6076-ff2f-4dc2-9ef1-17954f0341af.png)

**Comment by diemoschwarz** [comment]
just for fun: can we squeeze catart-mubu into a rectangular text-based icon?
```
C A T A
R T   — 
M U B U
```

```
C A M U
A R   B
T T - U
```

**Comment by christophertrapani** [comment]
That's a tough choice: The top one reads better to me, but I also like that
one can read CAMU in the lower one...

**Comment by diemoschwarz** [comment]
slightly more logical (but false leads in the rows)
```
C A M U
A R U
T T B
```
or the other way round (but then it's all about cats...)
```
C A T
A R T
M U B
U
```
4x4 (this is getting silly...)
```
C A T A
R T
-
M U B U
```

**Comment by christophertrapani** [comment]
We could put the CA MU in bold too:

*C A* T A
R T —
*M U *B U

or just

*C A* T A R T
*M U *B U —

**Comment by diemoschwarz** [comment]
once you start, there's no stoppin'
```
C     U
A     B
T     U
A R T M
```
```
A R T M
T     U
A     B
C     U
```
```
C A T A
      R
      T
U B U M
```
```
C     M
A     U
T     B
A R T U
```
```
C A T A
      R
      T
M U B U
```

**Comment by einbond** [comment]
Glad you both are having fun! Sorry I am still preoccupied with deadlines until mid-September, so I probably won’t be able to offer much content in my replies before then. But I favor emphasizing CAMU one way or the other in the logo, so I would vote for one of:
> slightly more logical (but false leads in the rows)
> 
> C A M U
> A R U
> T T B
> or the other way round (but then it's all about cats...)
> 
> C A T
> A R T
> M U B
> U
Cheers,

Aaron

**Comment by diemoschwarz** [comment]
here are 2 tries with what Fred and I deem the most readable layout:
<img height=200 src="https://user-images.githubusercontent.com/378151/186879225-ad61d98e-073d-4fe0-a52a-5e529d8fadad.png"/>
<img height=200 src="https://user-images.githubusercontent.com/378151/186879230-74c2673b-52d5-45a2-ad6a-694ca44d9259.png"/>

**Comment by christophertrapani** [comment]
Very nice! It conveys everything. I think I prefer option A with thinner letters, which makes CAMU more visible.

C
