### ISSUE TITLE
pyoracle-gl external missing

### ISSUE THREAD

**Issue by diemoschwarz** [Ircam-RnD/catart-mubu#68]
from [Arthur Sauer](https://discussion.forum.ircam.fr/u/sauer):

Open the catoracle+keymixer.maxpat patcher: pyoracle-gl external missing.

see https://discussion.forum.ircam.fr/t/pyoracle-gl-external-missing/42394

**Comment by einbond** [comment]
Deleting catoracle+keymixer.maxpat to avoid issues like this: I had updated catoracle, but I had not maintained catoracle+keymixer.maxpat which contained an outdated version of the pyoracle object. As no one of us is really using catoracle+keymixer.maxpat I propose that we delete it and leave it as an "exercise for the reader" if they wish to recombine modules in this way!
