### ISSUE TITLE
readfolder @recursive 1 - m4a files

### ISSUE THREAD

**Issue by christophertrapani** [Ircam-RnD/catart-mubu#69]
"readfolder @name audio @type audio @recursive 1" imports mp3 / aiff / wav but not m4a files

on the other hand, "readappend @name audio" loads .m4a files with no problem

Could we / should we standardize this?

**Comment by diemoschwarz** [comment]
sure? I have a mixed folder with mp3 / aiff / flac / m4a, and all files get imported.

**Comment by christophertrapani** [comment]
Interesting... Yes, I'm sure I've got this behavior in a particular patch.
Which are you using to test loading a recursive folder with m4a? Maybe then
I can isolate the culprit...

**Comment by christophertrapani** [comment]
For example: in the simple Patch, with a folder full of .m4a files: loading
via "readfolder" none are loaded. Loaded via "readappend," one at a time,
works fine.

**Comment by christophertrapani** [comment]
Merci pour le retour Riccardo. C'est étrange. J'essaie de vous envoyer le
petit dossier de 3 fichiers .m4a dont je me sers, avec un résultat nul
ici...

**Comment by christophertrapani** [comment]
voici le .zip (réduit à 2 fichiers dedans)
[samplefolderCT.zip](https://github.com/Ircam-RnD/catart-mubu/files/10579676/samplefolderCT.zip)

**Comment by RiccardoBorghesi** [comment]
non, le canzuna a la carrittera chargent sans probleme... ça doit être autre chose.

**Comment by christophertrapani** [comment]
Va bene: Disons que c'est un problème chez moi et pas un bug, et on peut
fermer cet issue...
