### ISSUE TITLE
catart-mubu-tutorial 8 tag not working

### ISSUE THREAD

**Issue by diemoschwarz** [Ircam-RnD/catart-mubu#71]
from https://discussion.forum.ircam.fr/t/catart-mubu-tutorial-5-tag-broken/43676/1:
> “catart-mubu-tutorial 5 tag” is not working.
First I thought it was because the tag bpatcher was not connected to mubu.
Connecting the in- and outlets to mubu, making a new inlet in camu.autotag for “alldone” from the analysis subpatcher did also not help.

any editing of buffer indices produces
`•error: buffer index out of range`

**Comment by christophertrapani** [comment]
I think this is one of Aaron's, and perhaps could be easily compared to / replaced by a working version in catoracle?
