### ISSUE TITLE
catoracle loading with wrong argument

### ISSUE THREAD

**Issue by einbond** [Ircam-RnD/catart-mubu#75]
Help! When loaded from pcontrol, catoracle has all #1 arguments replaced by 0 which makes it nonfunctional. Does anyone know how to load with a specific argument, or to load with #1 instead of 0?

**Comment by diemoschwarz** [comment]
cf. ref: 
> The word load, followed by the name of a patcher file, opens that file if it can be found in Max's search path. The file name may optionally be followed by up to nine numbers and/or symbols, which will be substituted for the appropriate changeable # arguments (#1 to #9) in the patch being opened.

**Comment by einbond** [comment]
Fixed, thanks!
