### ISSUE TITLE
import with directory recursion

### ISSUE THREAD

**Issue by diemoschwarz** [Ircam-RnD/catart-mubu#9]
should be simple with new mubu option

**Comment by diemoschwarz** [comment]
last point to fix: mubu readfolder message should accept just a filename to make patching easier, and report the range of added buffers

**Comment by diemoschwarz** [comment]
todo: make an abstraction camu.soundsets.tag that listens for readfolder/readappend messages and sets buffer info

**Comment by christophertrapani** [comment]
second for camu.soundsets.tag. Useful for the mvp+keymixer patch I'm building

**Comment by diemoschwarz** [comment]
what's the status on the soundset tagging patch?

**Comment by christophertrapani** [comment]
camu.soundsets.tag would still be very useful for me to finalize keymixer /
transcription patches

**Comment by einbond** [comment]
camu.soundset.tag done as specified in #13. Next step: customizable tags assigned to a range of buffer indices (either entered by user or, eventually, output by mubu when reading a folder). Should this be a separate module, or integrated into one larger module "camu.tag"?

**Comment by christophertrapani** [comment]
files must be in search path to be identified by "absolutepath," correct?
Not necessarily a problem, but needs to be specified in keymixer patch...

**Comment by einbond** [comment]
Yes, files need to be in the search path. But in catart-mubu files need to be in the search path to be saved/loaded in a corpus anyway, just like any max file. So this behavior is consistent, and should only come as a surprise to someone used to using catart classic.

**Comment by diemoschwarz** [comment]
files in search path no longer necessary,  output indices as necessary, @type audio restricts readfolder to audio files in all tutorials, this is DONE!
